name: pingmesh-agent docker publish

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: docker.io

jobs:
  generate-jobs:
    name: pingmesh-agent
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
          include:
          -
            name: pingmesh-agent
            image: dongjiang1989/pingmesh-agent
            file: ./Dockerfile
            platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x,linux/386

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - id: git-x
        run: |
          echo "::set-output name=git-version::$(git describe --tags --always)"
      - id: git-branch
        run: |
          echo "::set-output name=git-branch::$(echo ${GITHUB_REF##*/} | tr '[A-Z]' '[a-z]')"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2 
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.file }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ matrix.image }}:${{steps.git-branch.outputs.git-branch}}
            ${{ env.REGISTRY }}/${{ matrix.image }}:latest
      - name: Test ${{ matrix.name }}
        run: |
          docker pull ${{ env.REGISTRY }}/${{ matrix.image}}:${{steps.git-branch.outputs.git-branch}}
          docker image inspect ${{ env.REGISTRY }}/${{ matrix.image}}:${{steps.git-branch.outputs.git-branch}}
